[usuarios]
jonascosta    = "MENGo2026@"
rebecaalves   = "33091221"
wilsonalves   = "RR2026"
oficina       = "1234"
pedrobueno    = "oficina1234"
davifraga     = "oficina1234"
fabiomoraes   = "oficina1234"
wagnerandrade = "oficina1234"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/SEU_ID_AQUI"
# ... resto das suas configs do gsheets
